[workspace]
resolver = "2"
members = [
    "primitives",
    "consensus",
    "messaging",
    "substrate",
    "relayer",
    "evm",
    "fees",
    "fees/prisma-cli",
    "telemetry",
    "config",
]

[profile.release]
panic = "unwind"
opt-level = 3

[workspace.dependencies]
frame-support = { version = "28.0.0" }
sp-io = { version = "30.0.0" }
sp-core = { version = "28.0.0" }

sp-runtime = { version = "31.0.1" }
sp-mmr-primitives = { version = "26.0.0" }
polkadot-core-primitives = { version = "7.0.0" }

tesseract-substrate = { path = "./substrate" }
tesseract-evm = { path = "./evm" }
tesseract-primitives = { path = "./primitives" }
tesseract-consensus = { path = "./consensus" }
tesseract-messaging = { path = "./messaging" }

ethers = { git = "https://github.com/polytope-labs/ethers-rs", rev = "a61f4fd78cd9a417c74a1609e5007e17f0f0ebb4", features = ["ethers-solc"] }
ethers-contract-abigen = { git = "https://github.com/polytope-labs/ethers-rs", rev = "a61f4fd78cd9a417c74a1609e5007e17f0f0ebb4" }

merkle-mountain-range = { package = "ckb-merkle-mountain-range", version = "0.5.2" }
reconnecting-jsonrpsee-ws-client = { git = "https://github.com/polytope-labs/reconnecting-jsonrpsee-ws-client", rev = "7c0817478c2741cc0889e7c75c645aad9f3cbb55" }

# hyperbridge
beefy-verifier-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
beefy-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }

polygon-pos-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
polygon-pos-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
ismp-polygon-pos = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }

sync-committee-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
sync-committee-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
sync-committee-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
ismp-sync-committee = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
arbitrum-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
op-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
evm-common = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }

bsc-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
bsc-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
ismp-bsc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }

ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-ismp-demo = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-ismp-rpc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
ismp-solidity-abi = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
geth-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-ismp-relayer = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
mmr-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }

ethereum-trie = { git ="https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
subxt-utils = { git ="https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-ismp-host-executive = { git ="https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-hyperbridge = { git ="https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
pallet-mmr = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
substrate-state-machine = { git = "https://github.com/polytope-labs/hyperbridge", rev = "14a991228ae0d740696169e3d02d224683f9e8e6" }
